### ISSUE TITLE
Escape Pod name Collision

### ISSUE THREAD

**Issue by Matt-Ferus** [SWTCG/SWTCG-LACKEY#100]
Apologies if this has been brought up before but the Escape Pod (AGD Subordinate) has a name collision with the Escape Pod (BOY) in Lackey.

This also affects the STAP Squad Subordinate from AGD and Republic Assault Fleet from AGD.

All 3 of these dupicate names will be renamed in AGD Revisited:
Republic Assault Fleet (AGD) will become Republic Attack Force
STAP Squad (AGD) will become Separatist STAP Squad
Escape Pod (AGD) will become Republic Escape Pod

In the meantime, the name collisions for the current versions in Lackey can be fixed by adding (AGD) in parantheses to the AGD versions.

**Comment by ChrisMoExp** [comment]
this is a big coincidence, i literally just cam on here to raise an issue about the Escape pod collision.
Easy has pleaded to had the AGD in braces {} after the name and i have done that alreayd when i fixed Republic Assault Fleet.
I have just done the same for Escape Pod and will do the same for STAP Squad
