### ISSUE TITLE
BOH image differences

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#114]
A long term issue, but due to a previously incomplete rework of the set somewhere in the past we are left with some text in Lackey which doesn;t macth the images, whihc are out of sync with Cantina and the rerlease PDFs as well. 

[https://discord.com/channels/289835051322048515/663793386775511081/731183615446089749](url)
relating to this google folder:
[https://drive.google.com/drive/folders/1U9J-U6x2BEyq4Sl5uOwmFaNJYWObis42](url)

**Comment by CatraBuurenaar** [comment]
ight I'll work on that soon
