### ISSUE TITLE
Mando & The Child

### ISSUE THREAD

**Issue by Matt-Ferus** [SWTCG/SWTCG-LACKEY#123]
As you can see, the rulebook lists Mando and Child as different names for Din and Grogu.
Only they aren't in lackey; so to get them there, here are the "early promo" versions for them: 
:)

**Comment by Matt-Ferus** [comment]
![TMearlypromo_The_Child_A](https://user-images.githubusercontent.com/74730117/123336541-041cf180-d514-11eb-97c4-3f64c8421c13.jpg)
![TMearlypromo_The_Mandalorian_A](https://user-images.githubusercontent.com/74730117/123336550-08490f00-d514-11eb-8e75-b3667407cfec.jpg)

**Comment by ChrisMoExp** [comment]
added to TM sets, changed text.
