### ISSUE TITLE
TROS172 rarity conflict

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#128]
TROS172 General Hux (J) has an uncommon symbol on the card image but it displayed as Common in Cantina and Lackey

**Comment by Matt-Ferus** [comment]
Update here
https://drive.google.com/drive/folders/1WS4ht_VhN1AH5ypRm3mIHRG9farf2Add?usp=sharing

**Comment by ChrisMoExp** [comment]
fixed by 0966793dca25a5b13b01562325d79cdd6263859d [0966793]
