### ISSUE TITLE
TROS077 BB-8 (F) card text

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#137]
BB-8(F) and the promo both have a an extra word in the card text.

...Do 3 damage to **on** one of.....

**Comment by Matt-Ferus** [comment]
Card updated here:
https://drive.google.com/file/d/1o2uEkuiAarXLxSdxrJAefxN1jbrqRHwm/view?usp=sharing

and here:
https://drive.google.com/file/d/106KtGPJdvFkmturffWX0gU0OEJCgJT0Q/view?usp=sharing
