### ISSUE TITLE
BH072 card and text are inconsistent.

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#138]
Assassin is spelt wrong, and i think we were trying to change the text to qualify the effect to a Spy Character, but that doesn;t seem to be reflected in the image released in AAA release. @Matt-Ferus do we have an image for this or was i dreaming?

**Comment by Matt-Ferus** [comment]
Skill - Character 
already restricts it to Character - so the image was correct, except for the spelling of Assassin, which is now fixed
https://drive.google.com/file/d/1qx1NdoAHD2SdPZuY6UuO76WhjYlMZzjT/view?usp=sharing
