### ISSUE TITLE
ION067 card image needs a version

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#18]
If this is now version (A) please can the card image be updated to include it.

**Comment by MatthewLarson** [comment]
https://swtcg.com/Cards/Details/1181/Bravo-Five
@haec0007 or @Matt-Ferus, would either of you be willing to tackle this one?

**Comment by haec0007** [comment]
> https://swtcg.com/Cards/Details/1181/Bravo-Five
> @haec0007 or @Matt-Ferus, would either of you be willing to tackle this one?

I'm on it.
