### ISSUE TITLE
Separate PROMO set

### ISSUE THREAD

**Issue by haec0007** [SWTCG/SWTCG-LACKEY#25]
Should we separate all promo cards into their own set? As Tonrado pointed out on the Discord, a card with a promo version has double the chance of being drawn when opening packs for draft or sealed tournaments.

**Comment by MatthewLarson** [comment]
@haec0007 We should try this...

![](https://lackeyccg.com/images/plugintutorialcarddata.gif)

Notice how one of the cards has two image files. I am curious to see what this would do.

**Comment by MatthewLarson** [comment]
[https://lackeyccg.com/tutorialplugin.html](LackeyCCG Plugin Tutorial)

**Comment by haec0007** [comment]
> @haec0007 We should try this...
> 
> ![](https://camo.githubusercontent.com/a14561fc3bcbe7b71b8f2504d9a794a144105f9919da77d35a69e8d06e684d60/68747470733a2f2f6c61636b65796363672e636f6d2f696d616765732f706c7567696e7475746f7269616c63617264646174612e676966)
> 
> Notice how one of the cards has two image files. I am curious to see what this would do.

I like this solution better. Let's see if we can get it to work.

**Comment by ChrisMoExp** [comment]
I like the idea of having separate promo deck. 

The other thing i like about what is above is the numbers including leading zeroes, i was going to ask about this, now maybe this should be a separate issue, but either number them 001 002 etc would be better so they come up in order but if that doesn;t work maybe AOTC001 as the number? 

I ma also very curioius to see what two images in the same field would do.

**Comment by haec0007** [comment]
I just tried using two image files, and it didn't work. It was trying to find an image named "File1,File2.jpg". Closer inspection of the plugin tutorial reveals that the comma-separated images are for allowing multiple card backs:

> For cards with unique card backs, you need to do an extra step. In the plugininfo.txt file, you need to include the ISALLOWINGMULTIPLECARDBACKS argument (which is described on the plugininfo.txt creation tutorial page).
Once you have ISALLOWINGMULTIPLECARDBACKS defined, in the ImageFile column for that card, enter the 2 images separated by a comma (and no spaces). You can mix and match and have some cards with unique backs, and other cards with the normal default card back. Note in the example above, there is a card with a unique card back defined where Alpha001b is the unique card back image.

It looks like we may have to go back to a separate PROMO set. Is everyone in agreement that that is a good path forward?

**Comment by MatthewLarson** [comment]
I wish we could get in contact with the original developer and get him to change some of these things.

**Comment by ChrisMoExp** [comment]
does it include the subordinates in a sealed draw?

**Comment by haec0007** [comment]
> does it include the subordinates in a sealed draw?

I just tried opening a bunch of packs and didn't get any Subordinates. That's probably because their rarities are listed as "S." Maybe we could do the same thing for promos by changing the rarity to P?

**Comment by Matt-Ferus** [comment]
That would hopefully work.

I have nothing against them being a separate set either, but a P rarity would also fix the problem.
