### ISSUE TITLE
Republic Assault Fleet Name Collision

### ISSUE THREAD

**Issue by haec0007** [SWTCG/SWTCG-LACKEY#47]
Two cards have the same name:

RAW109 Republic Assault Fleet
AGD245 Republic Assault Fleet

**Comment by haec0007** [comment]
According to @Matt-Ferus this is flagged for correction in the AGD Revisited project.

**Comment by ChrisMoExp** [comment]
until we fix this the wrong card will be coming up for some people in their decks and how long away is the AGD revisit anyway?
@haec0007 and @Matt-Ferus I propose we fix temporarily by changing the name in Lackey for AGD245 to "Republic Assault Fleet AGD" for the time being. If neither of you object to that i'll action it in about a week.

**Comment by haec0007** [comment]
> until we fix this the wrong card will be coming up for some people in their decks and how long away is the AGD revisit anyway?
> @haec0007 and @Matt-Ferus I propose we fix temporarily by changing the name in Lackey for AGD245 to "Republic Assault Fleet AGD" for the time being. If neither of you object to that i'll action it in about a week.

That seems like a good temporary solution to me.
