### ISSUE TITLE
VP085 name spelt wrong on card

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#55]
Trasnport

**Comment by Matt-Ferus** [comment]
All the spelling/text phrasing errors pointed out in the Lackey card images recently have been uploaded to the pending TM Lackey Updates folder (VP085 is at the bottom):
https://drive.google.com/drive/folders/14Du6wBUIMRePm8cGTH_2JleHnLKvW_h0?usp=sharing

Full-sized images here:
https://drive.google.com/drive/folders/1BgYsQWAt0IqWfVz_vM1SH7EvRC-00q_7?usp=sharing
