### ISSUE TITLE
quotation mark inconsistency in set files

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#70]
this is liinked to #65 

Some of the set files have repetitions of double quotation marks. E.G. ION, line for BASS NASS (B). this leads to some of the card text lines haveing too maby quotation makrs in any section where quotations are used. This is likely caused by saving with a text qualifier of " at some point. Oddly it doesn't seem to have affected all lines consistently, so it may have been sometime ago. One must be careful to exclude text qualifier characters when saving the tab delimited set files. 

Some of the lines in that same file have single quotation marks.

I will correct double quotation marks by performing a find and replace on "" -> " where i find it. 

I will also remove single quotation marks where they are found and replace with double quotation marks. This will not be as easy since a find and replace might also find apostrophes (or characters intended as apostrophes).

**Comment by ChrisMoExp** [comment]
ION corrected last night
TUF also has problems

**Comment by ChrisMoExp** [comment]
TUF fixed by https://github.com/SWTCG/SWTCG-LACKEY/pull/72

**Comment by ChrisMoExp** [comment]
@MatthewLarson - we have a problem. 
One of our issues report is #65  in that issue report in the Lackey channel in Discord there is a screenshot of the names whihc are bad. When i look in my file for BOC.txt in the plugin folder at line 141 from the last release I see the problem. 
When i look at a copy i took recently before that release i don't see it.
When i look in the code repository in here i don;t see it. 

I can only conclude that there is some kind of problem with the files being altered between extraction from here and release, any ideas at which point??

**Comment by MatthewLarson** [comment]
> I can only conclude that there is some kind of problem with the files being altered between extraction from here and release, any ideas at which point??

@ChrisMoExp What software are you using to edit the txt files?

**Comment by ChrisMoExp** [comment]
I'm using OpenOffice then saving as tab delimited without text qualifier character. When I check the text after that in N++ it's good. When I look at what it looks like it's going to be like in the repo that looks good. 

I think a load and save cycle in OpenOffice fixes it but I'm wondering whether the extra quotation marks get added back in later on somehow.

**Comment by ChrisMoExp** [comment]
fixed by commits 683ab49 and 1675222
here's the fix:
edits have been made ehre the files were saved witha  text qualifier value of " in the delimited file filter/spec/format.
to correct them each file had to be opened and saved. I used OpenOffice and did save as, text CSV making sure to tick the edit filter setting undernetah the file name dialogue box, then when you get a chance to chose the text qualifier the " symbol must be deleted. 

note that opening a sets file as a text CSV in OpenOffice and saving it again without doing this re-introduces the problem. 

the problem can be detected using a find in files of <TAB>"  on the sets folder (without subfolders!) in N++
