### ISSUE TITLE
RS117 subordinate referenced in game text doesn;t exist

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#99]
card says "...take 1 40/3/3 Raptor Trooper Guard Subordinate..." but the one i find is called "Raptor Trooper Squad"... and is printed as such .

@Matt-Ferus one of these cards images needs to change:

1. change the text on RS117 to reference Raptor Trooper Squad
2. change the subordinate to be called "Raptor Trooper Guard" on the card and in Lackey

**Comment by Matt-Ferus** [comment]
I can change the text for RS117 to Raptor Trooper Squad.

**Comment by Matt-Ferus** [comment]
[https://drive.google.com/file/d/1SsifbKvSUkmREee9Y9UXgGS2wWGsKIj4/view?usp=sharing](url)
